### ISSUE TITLE
Parms did not appear to work for me (solved)

### ISSUE THREAD

**Issue by hunter1728** [alexandrenicol/aws-lambda-router-wn#1]
I found the examples in the extensive documentation a little confusing. They seemed to suggest something like this would work:

app.get('/example4?id=1', (request, response) => {
    const id = request.queryStringParameters.id;
    response(null, `Hello example4 {id} world`);
});

But it does not...  After some trial and error I was able to figure out that the parm names shouldn't be on the route.  Fwiw.

**Comment by alexandrenicol** [comment]
Hi @hunter1728 

Thanks for this, you are right this was confusing. 

I've updated the documentation, hopefully it makes more sense now. Let me know what you think and I'll close this issue.

The doc: https://alexandrenicol.github.io/aws-lambda-router-wn/#retrieve-parameters
The commit: https://github.com/alexandrenicol/aws-lambda-router-wn/commit/82051b03832acb124c906ff60eac78c5db21a720

**Comment by hunter1728** [comment]
Looks great - thanks! Thanks for writing this code!
